services:
  app:
    image: fireflyiii/core:version-6.4.16
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: postgres:17.5
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - ./firefly_iii_db:/var/lib/postgresql/data
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine:3.23.3
    restart: unless-stopped
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/PLEASE_REPLACE_WITH_32_CHAR_CODE;echo\"
      | crontab -
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
